INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (100, 'MYRENT SIGNATURE - CONTRATTO BREVE', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (101, 'MYRENT SIGNATURE - CONTRATTO LUNGO', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (102, 'MYRENT SIGNATURE - CONDIZIONI CONTRATTO', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (103, 'MYRENT SIGNATURE - PRENOTAZIONE', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (104, 'MYRENT SIGNATURE - PRIVACY', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (105, 'MYRENT SIGNATURE - PREVENTIVO BREVE', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (106, 'MYRENT SIGNATURE - PREVENTIVO LUNGO', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (107, 'MYRENT SIGNATURE - DOCUMENTO FISCALE', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (108, 'MYRENT SIGNATURE - INFORMATIVA FIRMA MYRENT SIGNATURE', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (109, 'MYRENT SIGNATURE - CONTRATTO BREVE CHIUSO', false, false, false);