INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (100, 'MYRENT SIGNATURE - Rental agreement short term', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (101, 'MYRENT SIGNATURE - Rental agreement long term', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (102, 'MYRENT SIGNATURE - Terms and conditions', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (103, 'MYRENT SIGNATURE - Reservation', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (104, 'MYRENT SIGNATURE - Privacy', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (105, 'MYRENT SIGNATURE - Sales quote short term', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (106, 'MYRENT SIGNATURE - Sales quote long term', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (107, 'MYRENT SIGNATURE - Invoice and receipt', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (108, 'MYRENT SIGNATURE - Disclosure MyRent Signature', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (109, 'MYRENT SIGNATURE - Rental agreement short term closed', false, false, false);