INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (100, 'MYRENT SIGNATURE - Contrato de alquiler a corto termime', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (101, 'MYRENT SIGNATURE - Contrato de alquiler de largo termime', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (102, 'MYRENT SIGNATURE - Condiciones', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (103, 'MYRENT SIGNATURE - Reserva', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (104, 'MYRENT SIGNATURE - PRIVACY', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (105, 'MYRENT SIGNATURE - Presupuesto corto', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (106, 'MYRENT SIGNATURE - Presupuesto largo', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (107, 'MYRENT SIGNATURE - Factura', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (108, 'MYRENT SIGNATURE - Información sobre la firma con MyRent Signature', false, false, false);
INSERT INTO documenti_contratto_noleggio (id, descrizione, visualizza, modifica, cancella) VALUES (109, 'MYRENT SIGNATURE - contrato de alquiler a corto termime cerrado', false, false, false);