INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (1, 'CONTADO', 'CT');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (2, 'VISA POS', 'VP');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (7, 'AMEX POS', 'AP');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (6, 'BANCOMAT', 'BP');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (8, 'DINERS POS', 'DP');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (9, 'AMEX OFFLINE', 'AX');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (10, 'VISA OFFLINE', 'BK');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (11, 'DINERS OFFLINE', 'DC');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (12, 'CONTADO, EFECTIVO', 'CH');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (4, 'VOUCHER', 'VR');
INSERT INTO mezzi_pagamenti (id, descrizione, codice) VALUES (13, 'RECIBIMIENTO DE FACTURA', 'VF');