INSERT INTO nazioni_iso (codice, nome) VALUES ('AD', 'ANDORRA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AE', 'EMIRATI ARABI UNITI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AF', 'AFGHANISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AG', 'ANTIGUA E BARBUDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AI', 'ANGUILLA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AL', 'ALBANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AM', 'ARMENIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AN', 'ANTILLE OLANDESI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AO', 'ANGOLA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AQ', 'ANTARTICO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AR', 'ARGENTINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AS', 'SAMOA AMERICANE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AT', 'AUSTRIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AU', 'AUSTRALIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AW', 'ARUBA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AX', 'ISOLE ALAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AZ', 'AZERBAIJAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BA', 'BOSNIA-ERZEGOVINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BB', 'BARBADOS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BD', 'BANGLADESH');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BE', 'BELGIO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BF', 'BURKINA FASO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BG', 'BULGARIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BH', 'BAHREIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BI', 'BURUNDI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BJ', 'BENIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BL', 'SAINT-BARTHELEMY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BM', 'BERMUDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BN', 'BRUNEI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BO', 'BOLIVIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BR', 'BRASILE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BS', 'BAHAMAS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BT', 'BHUTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BV', 'ISOLA BOUVET');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BW', 'BOTSWANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BY', 'BIELORUSSIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BZ', 'BELIZE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CA', 'CANADA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CC', 'ISOLE COCOS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CD', 'REPUBBLICA DEMOCRATICA DEL CONGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CF', 'REPUBBLICA CENTRAFRICANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CG', 'REPUBBLICA DEL CONGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CH', 'SVIZZERA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CI', 'COSTA D''AVORIO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CK', 'ISOLE COOK');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CL', 'CILE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CM', 'CAMERUN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CN', 'CINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CO', 'COLOMBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CR', 'COSTA RICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CU', 'CUBA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CV', 'CAPO VERDE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CX', 'ISOLA CHRISTMAS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CY', 'CIPRO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CZ', 'REPUBBLICA CECA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DE', 'GERMANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DJ', 'GIBUTI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DK', 'DANIMARCA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DM', 'DOMINICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DO', 'REPUBBLICA DOMINICANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DZ', 'ALGERIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EC', 'ECUADOR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EE', 'ESTONIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EG', 'EGITTO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EH', 'SAHARA OCCIDENTALE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ER', 'ERITREA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ES', 'SPAGNA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ET', 'ETIOPIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FI', 'FINLANDIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FJ', 'FIGI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FK', 'ISOLE FALKLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FM', 'MICRONESIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FO', 'ISOLE FAR OER');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FR', 'FRANCIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GA', 'GABON');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GB', 'GRAN BRETAGNA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GD', 'GRENADA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GE', 'GEORGIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GF', 'GUYANA FRANCESE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GG', 'GUERNSEY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GH', 'GHANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GI', 'GIBILTERRA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GL', 'GROENLANDIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GM', 'GAMBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GN', 'GUINEA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GP', 'GUADALUPA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GQ', 'GUINEA EQUATORIALE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GR', 'GRECIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GS', 'GEORGIA DEL SUD E ISOLE SANDWICH MERIDIONALI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GT', 'GUATEMALA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GU', 'GUAM');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GW', 'GUINEA-BISSAU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GY', 'GUYANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HK', 'HONG KONG');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HM', 'ISOLE HEARD E MCDONALD');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HN', 'HONDURAS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HR', 'CROAZIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HT', 'HAITI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HU', 'UNGHERIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ID', 'INDONESIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IE', 'IRLANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IL', 'ISRAELE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IM', 'ISOLA DI MAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IN', 'INDIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IO', 'TERRITORI BRITANNICI DELL''OCEANO INDIANO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IQ', 'IRAQ');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IR', 'IRAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IS', 'ISLANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IT', 'ITALIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JE', 'JERSEY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JM', 'GIAMAICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JO', 'GIORDANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JP', 'GIAPPONE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KE', 'KENYA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KG', 'KIRGHIZISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KH', 'CAMBOGIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KI', 'KIRIBATI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KM', 'COMORE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KN', 'SAINT KITTS E NEVIS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KP', 'COREA DEL NORD');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KR', 'COREA DEL SUD');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KW', 'KUWAIT');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KY', 'ISOLE CAYMAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KZ', 'KAZAKISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LA', 'LAOS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LB', 'LIBANO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LC', 'SANTA LUCIA COMMONWEALTH DI SANTA LUCIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LI', 'LIECHTENSTEIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LK', 'SRI LANKA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LR', 'LIBERIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LS', 'LESOTHO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LT', 'LITUANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LU', 'LUSSEMBURGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LV', 'LETTONIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LY', 'LIBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MA', 'MAROCCO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MC', 'MONACO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MD', 'MOLDAVIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ME', 'MONTENEGRO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MF', 'SAINT-MARTIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MG', 'MADAGASCAR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MH', 'ISOLE MARSHALL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MK', 'REPUBBLICA DI MACEDONIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ML', 'MALI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MM', 'BIRMANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MN', 'MONGOLIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MO', 'MACAO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MP', 'ISOLE MARIANNE SETTENTRIONALI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MQ', 'MARTINICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MR', 'MAURITANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MS', 'MONTSERRAT');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MT', 'MALTA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MU', 'MAURITIUS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MV', 'MALDIVE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MW', 'MALAWI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MX', 'MESSICO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MY', 'MALESIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MZ', 'MOZAMBICO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NA', 'NAMIBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NC', 'NUOVA CALEDONIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NE', 'NIGER');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NF', 'ISOLA NORFOLK');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NG', 'NIGERIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NI', 'NICARAGUA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NL', 'OLANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NO', 'NORVEGIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NP', 'NEPAL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NR', 'NAURU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NU', 'NIUE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NZ', 'NUOVA ZELANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('OM', 'OMAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PA', 'PANAMA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PE', 'PERU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PF', 'POLINESIA FRANCESE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PG', 'PAPUA NUOVA GUINEA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PH', 'FILIPPINE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PK', 'PAKISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PL', 'POLONIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PM', 'SAINT PIERRE E MIQUELON');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PN', 'ISOLE PITCAIRN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PR', 'PORTO RICO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PS', 'AUTORITA NAZIONALE PALESTINESE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PT', 'PORTOGALLO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PW', 'PALAU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PY', 'PARAGUAY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('QA', 'QATAR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RE', 'REUNION');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RO', 'ROMANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RU', 'RUSSIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RS', 'SERBIA REPUBBLICA DI SERBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RW', 'RUANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SA', 'ARABIA SAUDITA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SB', 'ISOLE SALOMONE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SC', 'SEYCHELLES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SD', 'SUDAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SE', 'SVEZIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SG', 'SINGAPORE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SH', 'SANT''ELENA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SI', 'SLOVENIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SJ', 'SVALBARD');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SK', 'REPUBBLICA SLOVACA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SL', 'SIERRA LEONE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SM', 'SAN MARINO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SN', 'SENEGAL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SO', 'SOMALIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SR', 'SURINAME');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ST', 'SAO TOME E PRINCIPE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SV', 'EL SALVADOR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SY', 'SIRIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SZ', 'SWAZILAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TC', 'ISOLE TURKS E CAICOS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TD', 'CIAD');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TF', 'TERRITORI FRANCESI DEL SUD');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TG', 'TOGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TH', 'THAILANDIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TJ', 'TAGIKISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TK', 'TOKELAU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TL', 'TIMOR EST');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TM', 'TURKMENISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TN', 'TUNISIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TO', 'TONGA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TR', 'TURCHIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TT', 'TRINIDAD E TOBAGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TV', 'TUVALU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TW', 'TAIWAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TZ', 'TANZANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UA', 'UCRAINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UG', 'UGANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UM', 'ISOLE MINORI ESTERNE DEGLI STATI UNITI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('US', 'STATI UNITI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UY', 'URUGUAY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UZ', 'UZBEKISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VA', 'CITTA DEL VATICANO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VC', 'SAINT VINCENT E GRENADINE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VE', 'VENEZUELA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VG', 'ISOLE VERGINI BRITANNICHE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VI', 'ISOLE VERGINI AMERICANE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VN', 'VIETNAM');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VU', 'VANUATU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('WF', 'WALLIS E FUTUNA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('WS', 'SAMOA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('YE', 'YEMEN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('YT', 'MAYOTTE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ZA', 'SUDAFRICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ZM', 'ZAMBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ZW', 'ZIMBABWE');