INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PY', 'PRY', 'PARAGUAY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PE', 'PER', 'PERÚ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PN', 'PCN', 'ISLAS PITCAIRN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PF', 'PYF', 'POLINESIA FRANCESA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PL', 'POL', 'POLONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PT', 'PRT', 'PORTUGAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PR', 'PRI', 'PUERTO RICO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('QA', 'QAT', 'QATAR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GB', 'GBR', 'REINO UNIDO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RE', 'REU', 'REUNIÓN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RW', 'RWA', 'RUANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RO', 'ROU', 'RUMANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RU', 'RUS', 'RUSIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EH', 'ESH', 'SAHARA OCCIDENTAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SB', 'SLB', 'ISLAS SALOMÓN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('WS', 'WSM', 'SAMOA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AS', 'ASM', 'SAMOA AMERICANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BL', 'BLM', 'SAN BARTOLOMÉ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KN', 'KNA', 'SAN CRISTÓBAL Y NIEVES');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SM', 'SMR', 'SAN MARINO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PM', 'SPM', 'SAN PEDRO Y MIQUELÓN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VC', 'VCT', 'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SH', 'SHN', 'SANTA HELENA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LC', 'LCA', 'SANTA LUCÍA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ST', 'STP', 'SANTO TOMÉ Y PRÍNCIPE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SN', 'SEN', 'SENEGAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RS', 'SRB', 'SERBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SC', 'SYC', 'SEYCHELLES');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SL', 'SLE', 'SIERRA LEONA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SG', 'SGP', 'SINGAPUR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SY', 'SYR', 'SIRIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SO', 'SOM', 'SOMALIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LK', 'LKA', 'SRI LANKA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SZ', 'SWZ', 'SUAZILANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ZA', 'ZAF', 'SUDÁFRICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SD', 'SDN', 'SUDÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SE', 'SWE', 'SUECIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CH', 'CHE', 'SUIZA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SR', 'SUR', 'SURINAM');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SJ', 'SJM', 'SVALBARD Y JAN MAYEN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TH', 'THA', 'TAILANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TW', 'TWN', 'TAIWÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TZ', 'TZA', 'TANZANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TJ', 'TJK', 'TAYIKISTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IO', 'IOT', 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TF', 'ATF', 'TERRITORIOS AUSTRALES FRANCESES');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TL', 'TLS', 'TIMOR ORIENTAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TG', 'TGO', 'TOGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TK', 'TKL', 'TOKELAU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TO', 'TON', 'TONGA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TT', 'TTO', 'TRINIDAD Y TOBAGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TN', 'TUN', 'TÚNEZ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TC', 'TCA', 'ISLAS TURCAS Y CAICOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TM', 'TKM', 'TURKMENISTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TR', 'TUR', 'TURQUÍA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TV', 'TUV', 'TUVALU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UA', 'UKR', 'UCRANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UG', 'UGA', 'UGANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UY', 'URY', 'URUGUAY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UZ', 'UZB', 'UZBEKISTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VU', 'VUT', 'VANUATU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VA', 'VAT', 'CIUDAD DEL VATICANO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VE', 'VEN', 'VENEZUELA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VN', 'VNM', 'VIETNAM');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VG', 'VGB', 'ISLAS VÍRGENES BRITÁNICAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VI', 'VIR', 'ISLAS VÍRGENES ESTADOUNIDENSES');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('WF', 'WLF', 'WALLIS Y FUTUNA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('YE', 'YEM', 'YEMEN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DJ', 'DJI', 'YIBUTI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ZM', 'ZMB', 'ZAMBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ZW', 'ZWE', 'ZIMBABUE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BR', 'BRA', 'BRASIL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BN', 'BRN', 'BRUNÉI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BG', 'BGR', 'BULGARIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BF', 'BFA', 'BURKINA FASO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BI', 'BDI', 'BURUNDI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BT', 'BTN', 'BUTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CV', 'CPV', 'CABO VERDE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KY', 'CYM', 'ISLAS CAIMÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KH', 'KHM', 'CAMBOYA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CM', 'CMR', 'CAMERÚN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CA', 'CAN', 'CANADÁ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CF', 'CAF', 'REPÚBLICA CENTROAFRICANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TD', 'TCD', 'CHAD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CZ', 'CZE', 'REPÚBLICA CHECA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CL', 'CHL', 'CHILE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CN', 'CHN', 'CHINA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CY', 'CYP', 'CHIPRE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CC', 'CCK', 'ISLAS COCOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CO', 'COL', 'COLOMBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KM', 'COM', 'COMORAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CG', 'COG', 'REPÚBLICA DEL CONGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CD', 'COD', 'REPÚBLICA DEMOCRÁTICA DEL CONGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CK', 'COK', 'ISLAS COOK');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KP', 'PRK', 'COREA DEL NORTE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KR', 'KOR', 'COREA DEL SUR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CI', 'CIV', 'COSTA DE MARFIL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CR', 'CRI', 'COSTA RICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HR', 'HRV', 'CROACIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CU', 'CUB', 'CUBA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DK', 'DNK', 'DINAMARCA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DM', 'DMA', 'DOMINICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DO', 'DOM', 'REPÚBLICA DOMINICANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EC', 'ECU', 'ECUADOR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EG', 'EGY', 'EGIPTO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SV', 'SLV', 'EL SALVADOR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AE', 'ARE', 'EMIRATOS ÁRABES UNIDOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ER', 'ERI', 'ERITREA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SK', 'SVK', 'ESLOVAQUIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SI', 'SVN', 'ESLOVENIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ES', 'ESP', 'ESPAÑA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('US', 'USA', 'ESTADOS UNIDOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UM', 'UMI', 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EE', 'EST', 'ESTONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ET', 'ETH', 'ETIOPÍA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FO', 'FRO', 'ISLAS FEROE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PH', 'PHL', 'FILIPINAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FI', 'FIN', 'FINLANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FJ', 'FJI', 'FIYI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FR', 'FRA', 'FRANCIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GA', 'GAB', 'GABÓN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GM', 'GMB', 'GAMBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GE', 'GEO', 'GEORGIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GS', 'SGS', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GH', 'GHA', 'GHANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GI', 'GIB', 'GIBRALTAR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GD', 'GRD', 'GRANADA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GR', 'GRC', 'GRECIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GL', 'GRL', 'GROENLANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GP', 'GLP', 'GUADALUPE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GU', 'GUM', 'GUAM');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GT', 'GTM', 'GUATEMALA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GF', 'GUF', 'GUAYANA FRANCESA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GG', 'GGY', 'GUERNSEY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GN', 'GIN', 'GUINEA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GQ', 'GNQ', 'GUINEA ECUATORIAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GW', 'GNB', 'GUINEA-BISSAU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GY', 'GUY', 'GUYANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HT', 'HTI', 'HAITÍ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HM', 'HMD', 'ISLAS HEARD Y MCDONALD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HN', 'HND', 'HONDURAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HK', 'HKG', 'HONG KONG');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HU', 'HUN', 'HUNGRÍA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IN', 'IND', 'INDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ID', 'IDN', 'INDONESIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IR', 'IRN', 'IRÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IQ', 'IRQ', 'IRAQ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IE', 'IRL', 'IRLANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IS', 'ISL', 'ISLANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IL', 'ISR', 'ISRAEL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IT', 'ITA', 'ITALIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JM', 'JAM', 'JAMAICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JP', 'JPN', 'JAPÓN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JE', 'JEY', 'JERSEY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JO', 'JOR', 'JORDANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KZ', 'KAZ', 'KAZAJISTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KE', 'KEN', 'KENIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KG', 'KGZ', 'KIRGUISTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KI', 'KIR', 'KIRIBATI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KW', 'KWT', 'KUWAIT');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LA', 'LAO', 'LAOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LS', 'LSO', 'LESOTO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LV', 'LVA', 'LETONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AF', 'AFG', 'AFGANISTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AX', 'ALA', 'ÅLAND');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AL', 'ALB', 'ALBANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DE', 'DEU', 'ALEMANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AD', 'AND', 'ANDORRA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AO', 'AGO', 'ANGOLA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AI', 'AIA', 'ANGUILA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AQ', 'ATA', 'ANTÁRTIDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AG', 'ATG', 'ANTIGUA Y BARBUDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AN', 'ANT', 'ANTILLAS NEERLANDESAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SA', 'SAU', 'ARABIA SAUDITA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DZ', 'DZA', 'ARGELIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AR', 'ARG', 'ARGENTINA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AM', 'ARM', 'ARMENIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AW', 'ABW', 'ARUBA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AU', 'AUS', 'AUSTRALIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AT', 'AUT', 'AUSTRIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AZ', 'AZE', 'AZERBAIYÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BS', 'BHS', 'BAHAMAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BH', 'BHR', 'BAHRÉIN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BD', 'BGD', 'BANGLADESH');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BB', 'BRB', 'BARBADOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BE', 'BEL', 'BÉLGICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BZ', 'BLZ', 'BELICE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BJ', 'BEN', 'BENÍN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BM', 'BMU', 'BERMUDAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BY', 'BLR', 'BIELORRUSIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MM', 'MMR', 'BIRMANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BO', 'BOL', 'BOLIVIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BA', 'BIH', 'BOSNIA Y HERZEGOVINA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BW', 'BWA', 'BOTSUANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BV', 'BVT', 'ISLA BOUVET');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LB', 'LBN', 'LÍBANO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LR', 'LBR', 'LIBERIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LY', 'LBY', 'LIBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LI', 'LIE', 'LIECHTENSTEIN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LT', 'LTU', 'LITUANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LU', 'LUX', 'LUXEMBURGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MO', 'MAC', 'MACAO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MK', 'MKD', 'MACEDONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MG', 'MDG', 'MADAGASCAR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MY', 'MYS', 'MALASIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MW', 'MWI', 'MALAUI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MV', 'MDV', 'MALDIVAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ML', 'MLI', 'MALÍ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MT', 'MLT', 'MALTA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FK', 'FLK', 'ISLAS MALVINAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IM', 'IMN', 'ISLA DE MAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MP', 'MNP', 'ISLAS MARIANAS DEL NORTE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MA', 'MAR', 'MARRUECOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MH', 'MHL', 'ISLAS MARSHALL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MQ', 'MTQ', 'MARTINICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MU', 'MUS', 'MAURICIO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MR', 'MRT', 'MAURITANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('YT', 'MYT', 'MAYOTTE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MX', 'MEX', 'MÉXICO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FM', 'FSM', 'MICRONESIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MD', 'MDA', 'MOLDAVIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MC', 'MCO', 'MÓNACO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MN', 'MNG', 'MONGOLIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ME', 'MNE', 'MONTENEGRO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MS', 'MSR', 'MONTSERRAT');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MZ', 'MOZ', 'MOZAMBIQUE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NA', 'NAM', 'NAMIBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NR', 'NRU', 'NAURU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CX', 'CXR', 'ISLA DE NAVIDAD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NP', 'NPL', 'NEPAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NI', 'NIC', 'NICARAGUA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NE', 'NER', 'NÍGER');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NG', 'NGA', 'NIGERIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NU', 'NIU', 'NIUE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NF', 'NFK', 'NORFOLK');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NO', 'NOR', 'NORUEGA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NC', 'NCL', 'NUEVA CALEDONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NZ', 'NZL', 'NUEVA ZELANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('OM', 'OMN', 'OMÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NL', 'NLD', 'PAÍSES BAJOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PK', 'PAK', 'PAKISTÁN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PW', 'PLW', 'PALAOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PS', 'PSE', 'TERRITORIOS PALESTINOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PA', 'PAN', 'PANAMÁ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PG', 'PNG', 'PAPÚA NUEVA GUINEA');
