INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AL', 'ALB', 'ALBANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DZ', 'DZA', 'ALGERIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AO', 'AGO', 'ANGOLA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AI', 'AIA', 'ANGUILLA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AQ', 'ATA', 'ANTARTICO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AN', 'ANT', 'ANTILLE OLANDESI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AR', 'ARG', 'ARGENTINA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AM', 'ARM', 'ARMENIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AW', 'ABW', 'ARUBA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AU', 'AUS', 'AUSTRALIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AT', 'AUT', 'AUSTRIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AZ', 'AZE', 'AZERBAIJAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BS', 'BHS', 'BAHAMAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BD', 'BGD', 'BANGLADESH');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BB', 'BRB', 'BARBADOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BE', 'BEL', 'BELGIO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BZ', 'BLZ', 'BELIZE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BM', 'BMU', 'BERMUDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BT', 'BTN', 'BHUTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BY', 'BLR', 'BIELORUSSIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MM', 'MMR', 'BIRMANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BO', 'BOL', 'BOLIVIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BW', 'BWA', 'BOTSWANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BR', 'BRA', 'BRASILE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BN', 'BRN', 'BRUNEI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BG', 'BGR', 'BULGARIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BF', 'BFA', 'BURKINA FASO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BI', 'BDI', 'BURUNDI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CM', 'CMR', 'CAMERUN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CA', 'CAN', 'CANADA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CV', 'CPV', 'CAPO VERDE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CL', 'CHL', 'CILE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CN', 'CHN', 'CINA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CO', 'COL', 'COLOMBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KM', 'COM', 'COMORE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KP', 'PRK', 'COREA DEL NORD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CI', 'CIV', 'COSTA D''AVORIO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CR', 'CRI', 'COSTA RICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HR', 'HRV', 'CROAZIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CU', 'CUB', 'CUBA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DK', 'DNK', 'DANIMARCA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DM', 'DMA', 'DOMINICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EG', 'EGY', 'EGITTO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AE', 'ARE', 'EMIRATI ARABI UNITI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ER', 'ERI', 'ERITREA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EE', 'EST', 'ESTONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ET', 'ETH', 'ETIOPIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PH', 'PHL', 'FILIPPINE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FI', 'FIN', 'FINLANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FR', 'FRA', 'FRANCIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GA', 'GAB', 'GABON');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GE', 'GEO', 'GEORGIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DE', 'DEU', 'GERMANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GH', 'GHA', 'GHANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JM', 'JAM', 'GIAMAICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JP', 'JPN', 'GIAPPONE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GI', 'GIB', 'GIBILTERRA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DJ', 'DJI', 'GIBUTI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JO', 'JOR', 'GIORDANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GR', 'GRC', 'GRECIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GD', 'GRD', 'GRENADA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GL', 'GRL', 'GROENLANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GP', 'GLP', 'GUADALUPA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GU', 'GUM', 'GUAM');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GG', 'GGY', 'GUERNSEY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GN', 'GIN', 'GUINEA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GW', 'GNB', 'GUINEA-BISSAU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GQ', 'GNQ', 'GUINEA EQUATORIALE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GY', 'GUY', 'GUYANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HT', 'HTI', 'HAITI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HN', 'HND', 'HONDURAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HK', 'HKG', 'HONG KONG');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IN', 'IND', 'INDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ID', 'IDN', 'INDONESIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IR', 'IRN', 'IRAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IE', 'IRL', 'IRLANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IS', 'ISL', 'ISLANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BV', 'BVT', 'ISOLA BOUVET');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CX', 'CXR', 'ISOLA CHRISTMAS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NF', 'NFK', 'ISOLA NORFOLK');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AX', 'ALA', 'ISOLE ALAND');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KY', 'CYM', 'ISOLE CAYMAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CC', 'CCK', 'ISOLE COCOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FO', 'FRO', 'ISOLE FAR OER');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FK', 'FLK', 'ISOLE FALKLAND');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HM', 'HMD', 'ISOLE HEARD E MCDONALD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MH', 'MHL', 'ISOLE MARSHALL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PN', 'PCN', 'ISOLE PITCAIRN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IL', 'ISR', 'ISRAELE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IT', 'ITA', 'ITALIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('JE', 'JEY', 'JERSEY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KZ', 'KAZ', 'KAZAKISTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KE', 'KEN', 'KENYA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KG', 'KGZ', 'KIRGHIZISTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KI', 'KIR', 'KIRIBATI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KW', 'KWT', 'KUWAIT');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LA', 'LAO', 'LAOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LV', 'LVA', 'LETTONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LB', 'LBN', 'LIBANO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LR', 'LBR', 'LIBERIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LY', 'LBY', 'LIBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LT', 'LTU', 'LITUANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LU', 'LUX', 'LUSSEMBURGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AF', 'AFG', 'AFGHANISTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AD', 'AND', 'ANDORRA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AG', 'ATG', 'ANTIGUA E BARBUDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SA', 'SAU', 'ARABIA SAUDITA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BH', 'BHR', 'BAHREIN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BJ', 'BEN', 'BENIN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BA', 'BIH', 'BOSNIA-ERZEGOVINA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KH', 'KHM', 'CAMBOGIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TD', 'TCD', 'CIAD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CY', 'CYP', 'CIPRO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VA', 'VAT', 'CITTA DEL VATICANO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KR', 'KOR', 'COREA DEL SUD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EC', 'ECU', 'ECUADOR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SV', 'SLV', 'EL SALVADOR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FJ', 'FJI', 'FIGI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GM', 'GMB', 'GAMBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GS', 'SGS', 'GEORGIA DEL SUD E ISOLE SANDWICH MERIDIONALI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GT', 'GTM', 'GUATEMALA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GF', 'GUF', 'GUYANA FRANCESE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IQ', 'IRQ', 'IRAQ');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IM', 'IMN', 'ISOLA DI MAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CK', 'COK', 'ISOLE COOK');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MP', 'MNP', 'ISOLE MARIANNE SETTENTRIONALI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UM', 'UMI', 'ISOLE MINORI ESTERNE DEGLI STATI UNITI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SB', 'SLB', 'ISOLE SALOMONE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VG', 'VGB', 'ISOLE VERGINI BRITANNICHE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VI', 'VIR', 'ISOLE VERGINI AMERICANE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LS', 'LSO', 'LESOTHO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LI', 'LIE', 'LIECHTENSTEIN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MO', 'MAC', 'MACAO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MK', 'MKD', 'REPUBBLICA DI MACEDONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MG', 'MDG', 'MADAGASCAR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MW', 'MWI', 'MALAWI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MY', 'MYS', 'MALESIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MV', 'MDV', 'MALDIVE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ML', 'MLI', 'MALI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MT', 'MLT', 'MALTA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MA', 'MAR', 'MAROCCO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MQ', 'MTQ', 'MARTINICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MR', 'MRT', 'MAURITANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MU', 'MUS', 'MAURITIUS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('YT', 'MYT', 'MAYOTTE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MX', 'MEX', 'MESSICO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('FM', 'FSM', 'MICRONESIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MD', 'MDA', 'MOLDAVIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MN', 'MNG', 'MONGOLIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ME', 'MNE', 'MONTENEGRO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MS', 'MSR', 'MONTSERRAT');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MZ', 'MOZ', 'MOZAMBICO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NA', 'NAM', 'NAMIBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NR', 'NRU', 'NAURU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NP', 'NPL', 'NEPAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NI', 'NIC', 'NICARAGUA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NE', 'NER', 'NIGER');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NG', 'NGA', 'NIGERIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NU', 'NIU', 'NIUE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NO', 'NOR', 'NORVEGIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NC', 'NCL', 'NUOVA CALEDONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NZ', 'NZL', 'NUOVA ZELANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('OM', 'OMN', 'OMAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('NL', 'NLD', 'OLANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PK', 'PAK', 'PAKISTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PW', 'PLW', 'PALAU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PS', 'PSE', 'AUTORITA NAZIONALE PALESTINESE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PA', 'PAN', 'PANAMA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PG', 'PNG', 'PAPUA NUOVA GUINEA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PY', 'PRY', 'PARAGUAY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PE', 'PER', 'PERU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PF', 'PYF', 'POLINESIA FRANCESE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PL', 'POL', 'POLONIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PR', 'PRI', 'PORTO RICO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PT', 'PRT', 'PORTOGALLO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MC', 'MCO', 'MONACO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('QA', 'QAT', 'QATAR');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('GB', 'GBR', 'GRAN BRETAGNA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CD', 'COD', 'REPUBBLICA DEMOCRATICA DEL CONGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CZ', 'CZE', 'REPUBBLICA CECA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CF', 'CAF', 'REPUBBLICA CENTRAFRICANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CG', 'COG', 'REPUBBLICA DEL CONGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('DO', 'DOM', 'REPUBBLICA DOMINICANA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RE', 'REU', 'REUNION');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RO', 'ROU', 'ROMANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RW', 'RWA', 'RUANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RU', 'RUS', 'RUSSIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('EH', 'ESH', 'SAHARA OCCIDENTALE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('KN', 'KNA', 'SAINT KITTS E NEVIS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LC', 'LCA', 'SANTA LUCIA COMMONWEALTH DI SANTA LUCIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SH', 'SHN', 'SANT''ELENA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VC', 'VCT', 'SAINT VINCENT E GRENADINE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('BL', 'BLM', 'SAINT-BARTHELEMY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('MF', 'MAF', 'SAINT-MARTIN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('PM', 'SPM', 'SAINT PIERRE E MIQUELON');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('WS', 'WSM', 'SAMOA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('AS', 'ASM', 'SAMOA AMERICANE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SM', 'SMR', 'SAN MARINO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ST', 'STP', 'SAO TOME E PRINCIPE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SN', 'SEN', 'SENEGAL');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('RS', 'SRB', 'SERBIA REPUBBLICA DI SERBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SC', 'SYC', 'SEYCHELLES');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SL', 'SLE', 'SIERRA LEONE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SG', 'SGP', 'SINGAPORE');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SY', 'SYR', 'SIRIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SK', 'SVK', 'REPUBBLICA SLOVACA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SI', 'SVN', 'SLOVENIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SO', 'SOM', 'SOMALIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ES', 'ESP', 'SPAGNA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('LK', 'LKA', 'SRI LANKA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('US', 'USA', 'STATI UNITI');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ZA', 'ZAF', 'SUDAFRICA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SD', 'SDN', 'SUDAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SR', 'SUR', 'SURINAME');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SJ', 'SJM', 'SVALBARD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SE', 'SWE', 'SVEZIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('CH', 'CHE', 'SVIZZERA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('SZ', 'SWZ', 'SWAZILAND');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TW', 'TWN', 'TAIWAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TJ', 'TJK', 'TAGIKISTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TZ', 'TZA', 'TANZANIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TF', 'ATF', 'TERRITORI FRANCESI DEL SUD');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('IO', 'IOT', 'TERRITORI BRITANNICI DELL''OCEANO INDIANO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TH', 'THA', 'THAILANDIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TL', 'TLS', 'TIMOR EST');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TG', 'TGO', 'TOGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TK', 'TKL', 'TOKELAU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TO', 'TON', 'TONGA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TT', 'TTO', 'TRINIDAD E TOBAGO');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TN', 'TUN', 'TUNISIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TR', 'TUR', 'TURCHIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TM', 'TKM', 'TURKMENISTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TC', 'TCA', 'ISOLE TURKS E CAICOS');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('TV', 'TUV', 'TUVALU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UA', 'UKR', 'UCRAINA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UG', 'UGA', 'UGANDA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('HU', 'HUN', 'UNGHERIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UY', 'URY', 'URUGUAY');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('UZ', 'UZB', 'UZBEKISTAN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VU', 'VUT', 'VANUATU');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VE', 'VEN', 'VENEZUELA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('VN', 'VNM', 'VIETNAM');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('WF', 'WLF', 'WALLIS E FUTUNA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('YE', 'YEM', 'YEMEN');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ZM', 'ZMB', 'ZAMBIA');
INSERT INTO nazioni_iso (codice, codice3, nome) VALUES ('ZW', 'ZWE', 'ZIMBABWE');
