INSERT INTO nazioni_iso (codice, nome) VALUES ('AD','ANDORRA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AE','UNITED ARAB EMIRATES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AF','AFGHANISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AG','ANTIGUA AND BARBUDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AI','ANGUILLA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AL','ALBANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AM','ARMENIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AN','NETHERLANDS ANTILLES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AO','ANGOLA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AQ','ANTARCTICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AR','ARGENTINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AS','AMERICAN SAMOA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AT','AUSTRIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AU','AUSTRALIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AW','ARUBA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AX','ALAND ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('AZ','AZERBAIJAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BA','BOSNIA AND HERZEGOVINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BB','BARBADOS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BD','BANGLADESH');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BE','BELGIUM');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BF','BURKINA FASO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BG','BULGARIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BH','BAHRAIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BI','BURUNDI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BJ','BENIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BL','SAINT BARTHELEMY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BM','BERMUDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BN','BRUNEI DARUSSALAM');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BO','BOLIVIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BR','BRAZIL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BS','BAHAMAS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BT','BHUTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BV','BOUVET ISLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BW','BOTSWANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BY','BELARUS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('BZ','BELIZE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CA','CANADA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CC','COCOS (KEELING) ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CF','CENTRAL AFRICAN REPUBLIC');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CG','CONGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CH','SWITZERLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CI','COTE D''IVOIRE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CK','COOK ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CL','CHILE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CM','CAMEROON');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CN','CHINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CO','COLOMBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CR','COSTA RICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CU','CUBA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CV','CAPE VERDE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CX','CHRISTMAS ISLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CY','CYPRUS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('CZ','CZECH REPUBLIC');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DE','GERMANY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DJ','DJIBOUTI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DK','DENMARK');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DM','DOMINICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DO','DOMINICAN REPUBLIC');
INSERT INTO nazioni_iso (codice, nome) VALUES ('DZ','ALGERIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EC','ECUADOR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EE','ESTONIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EG','EGYPT');
INSERT INTO nazioni_iso (codice, nome) VALUES ('EH','WESTERN SAHARA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ER','ERITREA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ES','SPAIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ET','ETHIOPIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FI','FINLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FJ','FIJI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FK','FALKLAND ISLANDS (MALVINAS)');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FM','MICRONESIA, FEDERATED STATES OF');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FO','FAROE ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('FR','FRANCE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GA','GABON');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GB','UNITED KINGDOM');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GD','GRENADA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GE','GEORGIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GF','FRENCH GUIANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GG','GUERNSEY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GH','GHANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GI','GIBRALTAR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GL','GREENLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GM','GAMBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GN','GUINEA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GP','GUADELOUPE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GQ','EQUATORIAL GUINEA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GR','GREECE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GT','GUATEMALA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GU','GUAM');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GW','GUINEA-BISSAU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('GY','GUYANA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HK','HONG KONG');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HM','HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HN','HONDURAS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HR','CROATIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HT','HAITI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('HU','HUNGARY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ID','INDONESIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IE','IRELAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IL','ISRAEL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IM','ISLE OF MAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IN','INDIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IO','BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IQ','IRAQ');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IR','IRAN, ISLAMIC REPUBLIC OF');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IS','ICELAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('IT','ITALY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JE','JERSEY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JM','JAMAICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JO','JORDAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('JP','JAPAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KE','KENYA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KG','KYRGYZSTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KH','CAMBODIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KI','KIRIBATI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KM','COMOROS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KN','SAINT KITTS AND NEVIS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KR','KOREA, REPUBLIC OF');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KW','KUWAIT');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KY','CAYMAN ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('KZ','KAZAKHSTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LB','LEBANON');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LC','SAINT LUCIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LI','LIECHTENSTEIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LK','SRI LANKA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LR','LIBERIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LS','LESOTHO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LT','LITHUANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LU','LUXEMBOURG');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LV','LATVIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('LY','LIBYAN ARAB JAMAHIRIYA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MA','MOROCCO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MC','MONACO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MD','MOLDOVA, REPUBLIC OF');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ME','MONTENEGRO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MF','SAINT MARTIN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MG','MADAGASCAR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MH','MARSHALL ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ML','MALI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MM','MYANMAR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MN','MONGOLIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MO','MACAO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MP','NORTHERN MARIANA ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MQ','MARTINIQUE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MR','MAURITANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MS','MONTSERRAT');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MT','MALTA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MU','MAURITIUS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MV','MALDIVES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MW','MALAWI');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MX','MEXICO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MY','MALAYSIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('MZ','MOZAMBIQUE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NA','NAMIBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NC','NEW CALEDONIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NE','NIGER');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NF','NORFOLK ISLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NG','NIGERIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NI','NICARAGUA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NL','NETHERLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NO','NORWAY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NP','NEPAL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NR','NAURU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NU','NIUE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('NZ','NEW ZEALAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('OM','OMAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PA','PANAMA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PE','PERU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PF','FRENCH POLYNESIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PG','PAPUA NEW GUINEA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PH','PHILIPPINES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PK','PAKISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PL','POLAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PM','SAINT PIERRE AND MIQUELON');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PN','PITCAIRN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PR','PUERTO RICO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PS','PALESTINIAN TERRITORY, OCCUPIED');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PT','PORTUGAL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PW','PALAU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('PY','PARAGUAY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('QA','QATAR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RE','REUNION');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RO','ROMANIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RS','SERBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RU','RUSSIAN FEDERATION');
INSERT INTO nazioni_iso (codice, nome) VALUES ('RW','RWANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SA','SAUDI ARABIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SB','SOLOMON ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SC','SEYCHELLES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SD','SUDAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SE','SWEDEN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SG','SINGAPORE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SH','SAINT HELENA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SI','SLOVENIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SJ','SVALBARD AND JAN MAYEN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SK','SLOVAKIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SL','SIERRA LEONE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SM','SAN MARINO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SN','SENEGAL');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SO','SOMALIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SR','SURINAME');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ST','SAO TOME AND PRINCIPE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SV','EL SALVADOR');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SY','SYRIAN ARAB REPUBLIC');
INSERT INTO nazioni_iso (codice, nome) VALUES ('SZ','SWAZILAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TC','TURKS AND CAICOS ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TD','CHAD');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TF','FRENCH SOUTHERN TERRITORIES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TG','TOGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TH','THAILAND');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TJ','TAJIKISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TK','TOKELAU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TL','TIMOR-LESTE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TM','TURKMENISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TN','TUNISIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TO','TONGA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TR','TURKEY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TT','TRINIDAD AND TOBAGO');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TV','TUVALU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TW','TAIWAN, PROVINCE OF CHINA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('TZ','TANZANIA, UNITED REPUBLIC OF');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UA','UKRAINE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UG','UGANDA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UM','UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO nazioni_iso (codice, nome) VALUES ('US','UNITED STATES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UY','URUGUAY');
INSERT INTO nazioni_iso (codice, nome) VALUES ('UZ','UZBEKISTAN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VA','HOLY SEE (VATICAN CITY STATE)');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VC','SAINT VINCENT AND THE GRENADINES');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VE','VENEZUELA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VG','VIRGIN ISLANDS, BRITISH');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VI','VIRGIN ISLANDS, U.S.');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VN','VIET NAM');
INSERT INTO nazioni_iso (codice, nome) VALUES ('VU','VANUATU');
INSERT INTO nazioni_iso (codice, nome) VALUES ('WF','WALLIS AND FUTUNA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('WS','SAMOA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('YE','YEMEN');
INSERT INTO nazioni_iso (codice, nome) VALUES ('YT','MAYOTTE');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ZA','SOUTH AFRICA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ZM','ZAMBIA');
INSERT INTO nazioni_iso (codice, nome) VALUES ('ZW','ZIMBABWE');
