INSERT INTO resources (descrizione) VALUES ('Primenote');
INSERT INTO resources (descrizione) VALUES ('Schede contabili');
INSERT INTO resources (descrizione) VALUES ('Archivi contabili');
INSERT INTO resources (descrizione) VALUES ('Fatturazione');
INSERT INTO resources (descrizione) VALUES ('Noleggio');
INSERT INTO resources (descrizione) VALUES ('Prenotazioni');
INSERT INTO resources (descrizione) VALUES ('Listini di tariffe');
INSERT INTO resources (descrizione) VALUES ('Anagrafiche clienti');
INSERT INTO resources (descrizione) VALUES ('Anagrafiche conducenti');
INSERT INTO resources (descrizione) VALUES ('Anagrafiche fornitori');
INSERT INTO resources (descrizione) VALUES ('Anagrafiche sedi');
INSERT INTO resources (descrizione) VALUES ('Parco veicoli');
INSERT INTO resources (descrizione) VALUES ('Gruppi di mezzi');
INSERT INTO resources (descrizione) VALUES ('Optionals');
INSERT INTO resources (descrizione) VALUES ('Fonti commissionabili');
INSERT INTO resources (descrizione) VALUES ('Carburanti');
INSERT INTO resources (descrizione) VALUES ('Movimenti');
INSERT INTO resources (descrizione) VALUES ('Proprietari Veicoli');
INSERT INTO resources (descrizione) VALUES ('Multe');
INSERT INTO resources (descrizione) VALUES ('Causali Movimenti');
INSERT INTO resources (descrizione) VALUES ('Sessioni Utenti');
INSERT INTO resources (descrizione) VALUES ('Gestione Cassa');