INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('VISA');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('VISA ELECTRON');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('AMERICAN EXPRESS');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('DINERS CLUB / CARTE BLANCHE');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('MASTERCARD');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('MAESTRO');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('SI');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('DISCOVER CARD');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('BANK CARD');
INSERT INTO tipi_carta_di_credito (descrizione) VALUES ('JCB');
