package it.myrent.ee.db;

import it.aessepi.utils.db.PersistentInstance;
import java.io.Serializable;
import java.util.Date;


/** @author Hibernate CodeGenerator */
public interface AnagraficaAzienda extends Serializable, PersistentInstance {

    public Integer getId();
    public void setId(Integer id);
    public void setCap (Integer cap);
    public Integer getCap();
    public void setCapProd(Integer capProd);
    public Integer getCapProd();
    public void setCapRiv(Integer capRiv);
    public Integer getCapRiv();
    public void setCellRiv(String cellRiv);
    public String getCellRiv ();
    public void setCitta(String citta);
    public String getCitta();
    public void setCittaProd (String cittaProd);
    public String getCittaProd();
    public void setCittaRiv(String cittaRiv);
    public String getCittaRiv();
    public void setCodiceDitta (Integer codiceDitta);
    public Integer getCodiceDitta ();
    public void setCodiceFiscale (String codiceFiscale);
    public String getCodiceFiscale ();
    public void setCodiceFiscaleProd(String codiceFiscaleProd);
    public String getCodiceFiscaleProd();
    public void setCodiceFiscaleRiv(String codiceFiscaleRiv);
    public String getCodiceFiscaleRiv();
    public void setCodiceRivenditore (Integer codiceRivenditore);
    public Integer getCodiceRivenditore ();
    public void setDataAttivazione(Date dataAttivazione);
    public Date getDataAttivazione();
    public void setDataUltimoAgg (Date dataUltimoAgg);
    public Date getDataUltimoAgg();
    public void setEmail(String email);
    public String getEmail();
    public void setEmailProd (String emailProd);
    public String getEmailProd ();
    public void setEmailRiv (String emailRiv);
    public String getEmailRiv();
    public void setFax (String fax);
    public String getFax();
    public void setFaxProd (String faxProd);
    public String getFaxProd();
    public void setFaxRiv(String faxRiv);
    public String getFaxRiv();
    public void setModuloCNT (Boolean moduloCNT);
    public Boolean getModuloCNT();
    public void setModuloNB(Boolean moduloNB);
    public Boolean getModuloNB();
    public void setModuloNL(Boolean moduloNL);
    public Boolean getModuloNL();
    public void setNazione(String nazione);
    public String getNazione();
    public void setNumero(String numero);
    public String getNumero();
    public void setNumeroAutoMezzi(Integer numeroAutoMezzi);
    public Integer getNumeroAutoMezzi();
    public void setNumeroRiv(String numeroRiv);
    public String getNumeroRiv();
    public void setNumeroProd(String numeroProd);
    public String getNumeroProd();
    public void setPartitaIva(String partitaIva);
    public String getPartitaIva();
    public void setPartitaIvaProd(String partitaIvaProd);
    public String getPartitaIvaProd();
    public void setPartitaIvaRiv(String partitaIvaRiv);
    public String getPartitaIvaRiv();
    public void setProvincia(String provincia);
    public String getProvincia();
    public void setProvinciaProd(String provinciaProd);
    public String getProvinciaProd();
    public void setProvinciaRiv(String provinciaRiv);
    public String getProvinciaRiv();
    public void setRagioneSociale(String ragioneSociale);
    public String getRagioneSociale();
    public void setRagioneSocialeProd(String ragioneSocialeProd);
    public String getRagioneSocialeProd();
    public void setRagioneSocialeRiv(String ragioneSocialeRiv);
    public String getRagioneSocialeRiv();
    public void setTelefono(String telefono);
    public String getTelefono();
    public void setTelProd(String telProd);
    public String getTelProd();
    public void setTelRiv(String telRiv);
    public String getTelRiv();
    public void setVia(String via);
    public String getVia();
    public void setViaProd(String viaProd);
    public String getViaProd();
    public void setViaRiv(String viaRiv);
    public String getViaRiv();
    public void setCalcoloTariffa(Integer calcoloTariffa);
    public Integer getCalcoloTariffa();
    public void setCodiceAttivazione (String codiceAttivazione);
    public String getCodiceAttivazione ();
    public void setCodiceRegistrazione (String codiceRegistrazione);
    public String getCodiceRegistrazione ();
}
