
package epayment.bbs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2018-01-10T12:51:57.205+05:30
 * Generated source version: 3.0.4
 */

@WebFault(name = "GenericError", targetNamespace = "http://schemas.datacontract.org/2004/07/BBS.EPayment.ServiceLibrary")
public class INetaxeptBatchGenericErrorFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.bbs_epayment.GenericError genericError;

    public INetaxeptBatchGenericErrorFaultFaultMessage() {
        super();
    }
    
    public INetaxeptBatchGenericErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public INetaxeptBatchGenericErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public INetaxeptBatchGenericErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.bbs_epayment.GenericError genericError) {
        super(message);
        this.genericError = genericError;
    }

    public INetaxeptBatchGenericErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.bbs_epayment.GenericError genericError, Throwable cause) {
        super(message, cause);
        this.genericError = genericError;
    }

    public org.datacontract.schemas._2004._07.bbs_epayment.GenericError getFaultInfo() {
        return this.genericError;
    }
}
