
package epayment.bbs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2018-01-10T12:51:57.278+05:30
 * Generated source version: 3.0.4
 */

@WebFault(name = "UniqueTransactionIdException", targetNamespace = "http://schemas.datacontract.org/2004/07/BBS.EPayment.ServiceLibrary")
public class INetaxeptRegisterUniqueTransactionIdExceptionFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.bbs_epayment.UniqueTransactionIdException uniqueTransactionIdException;

    public INetaxeptRegisterUniqueTransactionIdExceptionFaultFaultMessage() {
        super();
    }
    
    public INetaxeptRegisterUniqueTransactionIdExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public INetaxeptRegisterUniqueTransactionIdExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public INetaxeptRegisterUniqueTransactionIdExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.bbs_epayment.UniqueTransactionIdException uniqueTransactionIdException) {
        super(message);
        this.uniqueTransactionIdException = uniqueTransactionIdException;
    }

    public INetaxeptRegisterUniqueTransactionIdExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.bbs_epayment.UniqueTransactionIdException uniqueTransactionIdException, Throwable cause) {
        super(message, cause);
        this.uniqueTransactionIdException = uniqueTransactionIdException;
    }

    public org.datacontract.schemas._2004._07.bbs_epayment.UniqueTransactionIdException getFaultInfo() {
        return this.uniqueTransactionIdException;
    }
}
