package epayment.bbs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2018-01-10T12:51:57.454+05:30
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "Netaxept", 
                  wsdlLocation = "file:web-service-references/Netaxept.svc.singlewsdl.wsdl",
                  targetNamespace = "http://BBS.EPayment") 
public class Netaxept extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://BBS.EPayment", "Netaxept");
    public final static QName Endpoint = new QName("http://BBS.EPayment", "Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:web-service-references/Netaxept.svc.singlewsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Netaxept.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:web-service-references/Netaxept.svc.singlewsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Netaxept(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Netaxept(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Netaxept() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Netaxept(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Netaxept(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Netaxept(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns INetaxept
     */
    @WebEndpoint(name = "Endpoint")
    public INetaxept getEndpoint() {
        return super.getPort(Endpoint, INetaxept.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INetaxept
     */
    @WebEndpoint(name = "Endpoint")
    public INetaxept getEndpoint(WebServiceFeature... features) {
        return super.getPort(Endpoint, INetaxept.class, features);
    }

}
